### ISSUE TITLE
Manual install doesn't show what changes need to be made to web/index.html

### ISSUE THREAD

**Issue by joshobrienau** [diesys/transmission-web-soft-theme#1]
Hi, 
The installation instructions don't show what changes need to be made to "web/index.html" to enable transmission-web-soft-theme. Can you please update with the changes required to "web/index.html" to enable this theme?

Thanks

**Comment by nathanrdodson** [comment]
> Hi,
> The installation instructions don't show what changes need to be made to "web/index.html" to enable transmission-web-soft-theme. Can you please update with the changes required to "web/index.html" to enable this theme?
> 
> Thanks

Josh, did you ever figure this issue out?

**Comment by joshobrienau** [comment]
> > Hi,
> > The installation instructions don't show what changes need to be made to "web/index.html" to enable transmission-web-soft-theme. Can you please update with the changes required to "web/index.html" to enable this theme?
> > Thanks
> 
> Josh, did you ever figure this issue out?

Unfortunately not, looks as though this is not maintained, I’ve made changes to the base Transmission theme to suit my needs for now, but I did like the look of this one, ah well.

**Comment by punkrockgirl** [comment]
Ok so once copied the content to the /usr/share/transmission/web folder —replacing those files that need to be replaced— this is what I did:
add the following two lines in between IE8 stylesheet and before the scripts [in the head]:

`<link href="./style/transmission/soft-theme.min.css" type="text/css" rel="stylesheet" />`
`<link href="style/transmission/soft-dark-theme.min.css" type="text/css" rel="stylesheet" />`

That's for the dark theme, and if you like the light one better:

`<link href="./style/transmission/soft-theme.min.css" type="text/css" rel="stylesheet" />`
`<link href="style/transmission/soft-light-theme.min.css" type="text/css" rel="stylesheet" />`

It took me a while to figure it out myself.

**Comment by diesys** [comment]
I'm really sorry guys, I'm reading only now.
Usually i keep more updated my gitlab repo: https://git.eigenlab.org/sbiego/transmission-web-soft-theme/

and there was - hoping a better - guide here: https://git.eigenlab.org/sbiego/transmission-web-soft-theme/wikis/Enable-disable-theme

**Comment by diesys** [comment]
the link is present in the readme and i added the lines for enabling themes too
