### ISSUE TITLE
How to enable theme?

### ISSUE THREAD

**Issue by neo-neo1** [diesys/transmission-web-soft-theme#2]
I'm a bit lost, the instructions are lacking in detail. 

How exactly do I enable the "dark theme" portion of the CSS? I already copied all the files over. 

What am I supposed to edit inside of index.html? Instructions are vague and don't make sense to me.

**Comment by neo-neo1** [comment]
Found the answer here, seems other users had the same issue. Would be ideal if this was added to the wiki. 

https://github.com/diesys/transmission-web-soft-theme/issues/1#issuecomment-619279477




    Add the following two lines in between IE8 stylesheet and before the scripts [in the head]:

    <link href="./style/transmission/soft-theme.min.css" type="text/css" rel="stylesheet" />
    <link href="style/transmission/soft-dark-theme.min.css" type="text/css" rel="stylesheet" />

    That's for the dark theme, and if you like the light one better:

    <link href="./style/transmission/soft-theme.min.css" type="text/css" rel="stylesheet" />
    <link href="style/transmission/soft-light-theme.min.css" type="text/css" rel="stylesheet" />

**Comment by diesys** [comment]
https://git.eigenlab.org/sbiego/transmission-web-soft-theme/wikis/Enable-disable-theme

**Comment by diesys** [comment]
the link is present in the readme and i added the lines for enabling themes too
